substitutions:
  _VITE_IDENTITY_API_URL: ""
  _VITE_INVENTORY_API_URL: ""
  _VITE_INTELLIGENCE_API_URL: ""

steps:
  - id: Deploy to App Engine Standard
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
        gcloud app deploy app.yaml \
          --quiet

options:
  logging: CLOUD_LOGGING_ONLY
